version: '3.7'
services:
  laravel:
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    depends_on:
      - redis
      - db
  redis:
    image: redis:5-alpine
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: laravel
      POSTGRES_DB: formail
      POSTGRES_PASSWORD: laravel
    volumes:
      - data:/var/lib/postgressql/data
volumes:
  data:
